version: '3'
services:
    php:
        restart: always
        build:
            context: .
        ports:
            - ${HTTP_PORT:-80}:${HTTP_PORT:-80}
        volumes:
            - .:/app/
        networks:
            - backend
        depends_on:
            - redis
        env_file:
            - .env
        ulimits:
            nproc: 65535
            nofile:
                soft: 20000
                hard: 40000
        logging:
            driver: 'json-file'
            options:
                max-size: '50m'
    redis:
        image: 'redis:alpine'
        restart: always
        volumes:
            - ./redis/redis-data:/data
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - backend
        command: 'redis-server'
        logging:
            driver: 'json-file'
            options:
                max-size: '50m'
    mysql:
        build:
            context: ./mysql/
            dockerfile: Dockerfile
        restart: always
        volumes:
            - db:/bitnami/mariadb/data
        networks:
            - backend
        env_file:
            - ./mysql/.env
        logging:
            driver: 'json-file'
            options:
                max-size: '50m'
volumes:
    db:
        driver: local
networks:
    backend:
        driver: bridge
